<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="U2IWIN10PLP" name="Registration" tests="13" failures="2" timestamp="25 Jun 2019 07:20:07 GMT" time="209.51" errors="0">
  <testcase name="onlyName" time="103.516" classname="com.test.DataDrivenCSVReadRegistrationTest"/>
  <testcase name="onlyName" time="80.671" classname="com.test.DataDrivenCSVReadRegistrationTest"/>
  <testcase name="atestOne" time="0.002" classname="com.test.TestNGBasics"/>
  <testcase name="btestOne" time="0.014" classname="com.test.TestNGBasics"/>
  <testcase name="ctestOne" time="0.0" classname="com.test.TestNGBasics"/>
  <testcase name="dtestOne" time="4.002" classname="com.test.TestNGBasics">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.test.TestNGBasics.dtestOne(TestNGBasics.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- dtestOne -->
  <testcase name="etestOne" time="4.001" classname="com.test.TestNGBasics"/>
  <testcase name="ftestOne" time="4.002" classname="com.test.TestNGBasics"/>
  <testcase name="i_exceptionTest" time="0.001" classname="com.test.TestNGBasics"/>
  <testcase name="l_enabledTest" time="0.0" classname="com.test.TestNGBasics"/>
  <testcase name="g_dependsOnFPass_ShouldFail" time="0.001" classname="com.test.TestNGBasics">
    <failure type="junit.framework.AssertionFailedError" message="expected:&amp;lt;10&amp;gt; but was:&amp;lt;4&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: expected:<10> but was:<4>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:282)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:201)
	at junit.framework.Assert.assertEquals(Assert.java:207)
	at com.test.TestNGBasics.g_dependsOnFPass_ShouldFail(TestNGBasics.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- g_dependsOnFPass_ShouldFail -->
  <testcase name="h_dependsOnFail" time="0.0" classname="com.test.TestNGBasics">
    <skipped/>
  </testcase> <!-- h_dependsOnFail -->
  <testcase name="j_dependsOnFail_alwasyRun" time="0.0" classname="com.test.TestNGBasics"/>
</testsuite> <!-- Registration -->
